[gcp_service_account]
type = "service_account"
project_id = "white-watch-449907-p3"
private_key_id = "1b4364cc8b6ce0e1cb4641fbc8a17423668d8466"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkq... (nội dung đầy đủ)\n-----END PRIVATE KEY-----\n"
client_email = "shelf-life-data@white-watch-449907-p3.iam.gserviceaccount.com"
client_id = "108049648474883772147"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/shelf-life-data@white-watch-449907-p3.iam.gserviceaccount.com"

[sheet]
url = "https://docs.google.com/spreadsheets/d/1vecIMURZu5K_AZkd3WqgbzS3SYhoVYChPL0ZCIa7uDo/edit?usp=sharing"
